name: porteurdvie_beta
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.0.0
  image_cropper: ^1.4.0
  
  #new dependencies_for_a_project
  #smart_select: ^4.3.2
  # awesome_select:
  #   git:
  #     url: https://github.com/iktakahiro/flutter_awesome_select.git
  #     ref: master
  shared_preferences: ^2.0.5
  get: ^4.1.4
  cool_stepper: ^1.1.3
  simple_animations: ^1.3.3
  flutter_localizations:
    sdk: flutter
  grouped_buttons: ^1.0.4
  google_fonts: ^2.1.0
  #custom_radio: ^0.1.2
  dio: ^4.0.0
  http: ^0.13.0+4
  pretty_dio_logger: ^1.1.1
  json_serializable: ^3.5.1
  #ui design
  getwidget: ^2.0.3
  # Logging
  logger: ^0.8.3
  #formulaire datatable multiimage picker
  snippet_coder_utils: ^1.0.6
  font_awesome_flutter: ^9.1.0
  #image picker
  image_picker: ^0.7.5+4
  #splashscreen: ^1.3.5
  #fancy_drawer: ^1.0.0
  just_audio: ^0.9.5
  url_launcher: ^6.0.10
  sentry_flutter: ^6.0.1
  jiffy: ^4.1.0

  uuid: ^3.0.5

  #cinetpay
  flutter_inappwebview: ^5.3.2
 #native_pdf_view: any
  flutter_cache_manager: ^3.3.0
  new_version: ^0.3.0
  intl_phone_field: ^3.1.0
  pdfx: ^2.2.0

  #phone_number: ^1.0.0
  #intl_phone_number_input: ^0.7.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/ca/
    - assets/logos/
    - assets/images/
    - assets/icons/
    - assets/html/cinetpay.html
    - assets/pdf/REGLEMENT_INTERIEUR_PDV_SESSION_MAI_2020.pdf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
